#! /usr/local/bin/perl

use strict;
use warnings;

use Benchmark qw< cmpthese >;

use PlainMoose;
use FancyMoose;


use constant COUNT => 1000;

my $plain_moose = PlainMoose->new;
my $fancy_moose = FancyMoose->new;

cmpthese(100_000, {
    plain_moose =>  sub { $plain_moose->doit(count => COUNT, msg => 'testing some shite') },
    fancy_moose =>  sub { $fancy_moose->doit(count => COUNT, msg => 'testing some shite') },
});

